#!/bin/bash
# Usage: ./set-common-dev <repo> [package [org]] [--http]
# Org defaults to 'pcdshub', package defaults to repo name
# Defaults to ssh remote, use --http if you prefer that

if [ -z "$1" ]; then
  echo "Usage: ./set-common-dev <repo> [package [org]]" >&2
  exit 1
fi

REPO="$1"
PACKAGE=${2:-${MODULE}}
ORG=${3:-"pcdshub"}

HERE=`dirname $(readlink -f $0)`
mkdir -p "${HERE}/../common/dev/devpath"

pushd "${HERE}/../common/dev"

if [ ! -d "${REPO}" ]; then
  if [[ "$@" =~ "--http" ]]; then
    git clone "https://github.com/${ORG}/${REPO}.git"
  else
    git clone "git@github.com:${ORG}/${REPO}.git"
  fi
  ln -s `readlink -f "${REPO}/${PACKAGE}"` "devpath/${PACKAGE}"
fi

popd
