#!/bin/bash
# Source this to load the full environment that hutch python uses

# edit this line only
export CONDA_ENVNAME="pcds-2.3.4"
export CONDA_BASE="/reg/g/pcds/pyps/conda/py36"
export HUTCH="xpp"

unset PYTHONPATH
unset LD_LIBRARY_PATH

source "${CONDA_BASE}/etc/profile.d/conda.sh"
conda activate "${CONDA_ENVNAME}"
HERE=`dirname $(readlink -f $BASH_SOURCE)`
export PYTHONPATH="${HERE}:${HERE}/dev/devpath"
source pcdsdaq_lib_setup
export CONDA_PROMPT_MODIFIER="(${HUTCH}-${CONDA_ENVNAME})"
